apiVersion: v1
kind: Service
metadata:
  name: redis-replica
spec:
  clusterIP: None  # Service Headless
  selector:
    app: redis
    role: replica
  ports:
    - port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-replica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      containers:
        - name: redis
          image: redis:7
          command: ["redis-server"]
          args: ["--replicaof", "redis-master", "6379"]
          ports:
            - containerPort: 6379
