apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: redis-node-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_URL
              value: redis://redis-master:6379
            - name: REDIS_REPLICAS_URL
              value: redis://redis-replica:6379
